apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: myApp-pprd
images:
- name: App-docker-scratch-intranet/myApp/myApp
  newName: myApp-docker-stable-intranet/myApp/myApp
  newTag: 1.6.18
patchesJson6902:
- path: app_ingress_patch.json
  target:
    group: networking.k8s.io
    kind: Ingress
    name: myApp
    version: v1
patchesStrategicMerge:
- increase_replicas.yaml
resources:
- ../base
- myApp-vaultsecret.yaml
configMapGenerator:
- files:
    - config/hibernate.properties
    - config/log4j2.xml
    - config/application-persistence.xml
  name: myApp-config
- literals:
  - DB_CONNECTION_URL=jdbc:db2://---------
  - WS_URL=http://-----------
  name: server-conf
