apiVersion: apps/v1
kind: Deployment
metadata:
  name: myApp
spec:
  replicas: 2 #CHANGEMENT DU NOMBRE DE PODS
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
